namespace Infrastructure.Constants
{
    public class StudentStatusConstants
    {
        public const string Active = "active";
        public const string Interrupted = "interrupted";
        public const string Completed = "completed";
        public const string Graduated = "graduated";
        public const string ProcessGraduation = "processGraduation";
        // Id's must no change they are generated by us, not by the database
        public const int GraduatedId = 5;
    }
}
